easy_admin:
    entities:
        Career:
            class: App\Entity\Career
            list:
                title: 'Вакансии'
                actions:
                - { name: 'new', label: 'Добавить'}
                - { name: 'edit', label: 'Редактировать'}
                - { name: 'delete', label: 'Удалить'}
                - { name: 'search', label: 'Поиск'}

                fields:
                    - { property: 'id', type: 'text',  }
                    - { property: 'vakancy', type: 'text', label: 'Вакансия'}
            new:
                title: 'Добавить Вакансию'
                actions:
                - { name: 'save', label: 'Сохранить'}
                - { name: 'list', label: 'Вернуться к сиску'}
                fields:
                    - { property: 'vakancy', type: 'text', label: 'Название вакансии' }
                    - { property: 'description', type: 'textarea', label: 'Описание', css_class: "ckeditor", }
                    - { property: 'imageFile', type: 'file'}
            edit:
                title: 'Редактировать Вакансию'
                actions:
                - { name: 'list', label: 'Вернуться к сиску'}
                - { name: 'delete', label: 'Удалить'}
                fields:
                    - { property: 'vakancy', type: 'text', label: 'Название вакансии' }
                    - { property: 'description', type: 'textarea', label: 'Описание', css_class: "ckeditor", }
                    - { property: 'imageFile', type: 'vich_image'}